version: "3"

services:

    api:
      build:
        context: .
        args:
          - uid=${UID}
          - gid=${GID}
      container_name: pmcserver
      user: "${UID}:${GID}"
      depends_on:
        pulp-api:
          condition: service_healthy
        db:
          condition: service_started
      volumes:
        - ./app:/pmcserver/app
        - ./setup.cfg:/pmcserver/setup.cfg
        - ./tests:/pmcserver/tests
        - ./migrations:/pmcserver/migrations
      ports:
        - "8000:8000"
      env_file:
        - .env

    db:
      image: postgres
      container_name: db
      ports:
        - 5432:5432
      volumes:
        - postgres-data:/var/lib/postgresql/data
        - ../pulp/pulp_db_init.sh:/docker-entrypoint-initdb.d/01_pulp_db_init.sh
      env_file:
        - .env

    signer:
      image: signer
      build:
        context: ../signer
      container_name: signer
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8888/status"]
        interval: 5s
        timeout: 1s
        retries: 5
      ports:
        - "8888:8888"
      volumes:
        - ../server/.test.key:/mnt/test.key
      env_file:
        - ../server/.env

    pulp-api:
      image: localhost/pulp:stable
      build:
        context: ../pulp
      container_name: pulp-api
      command: pulp-api
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:24817/pulp/api/v3/status/"]
        interval: 5s
        timeout: 1s
        retries: 30
      depends_on:
        db:
          condition: service_started
      ports:
        - "8080:24817"
      volumes:
        - ../pulp/settings.py:/etc/pulp/settings.py
        - ../pulp/.pulp_symmetric_key:/etc/pulp/pulp_symmetric_key
        - pulp_storage:/var/lib/pulp
        - containers:/var/lib/containers
      devices:
        - /dev/fuse
      env_file:
        - ../server/.env

    pulp-worker:
      image: localhost/pulp:stable
      build:
        context: ../pulp
      container_name: pulp-worker
      command: pulp-worker
      depends_on:
        signer:
          condition: service_healthy
        db:
          condition: service_started
      volumes:
        - ../pulp/settings.py:/etc/pulp/settings.py
        - ../pulp/.pulp_symmetric_key:/etc/pulp/pulp_symmetric_key
        - ../server/.test.pub:/sign_cli/msopentech.asc  # overwrite the MS OpenTech pub key 
        - pulp_storage:/var/lib/pulp
        - containers:/var/lib/containers
      devices:
        - /dev/fuse
      env_file:
        - ../server/.env

    pulp-content:
      image: localhost/pulp:stable
      build:
        context: ../pulp
      container_name: pulp-content
      command: pulp-content
      depends_on:
        db:
          condition: service_started
      ports:
        - "8081:24816"
      volumes:
        - ../pulp/settings.py:/etc/pulp/settings.py
        - ../pulp/.pulp_symmetric_key:/etc/pulp/pulp_symmetric_key
        - pulp_storage:/var/lib/pulp
        - containers:/var/lib/containers
      devices:
        - /dev/fuse
      env_file:
        - ../server/.env

volumes:
  pulp_storage:
  containers:
  postgres-data:
