[tool.poetry]
name = "pmcserver"
version = "0.0.1"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.75.0"
uvicorn = "0.17.6"
python-dotenv = "^0.19.2"
httpx = "^0.22.0"
python-multipart = "^0.0.5"
sqlmodel = "^0.0.6"
asyncpg = "^0.25.0"
alembic = "^1.7.7"
email-validator = "^1.1.3"
asgi-correlation-id = "^3.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.10.1"
flake8 = "^4.0.1"
mypy = "^0.940"

[tool.black]
line-length = 100

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
