apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmc
  template:
    metadata:
      labels:
        app: pmc
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: pmc
        image: $loginserver/pmcserver_api:latest
        resources:
          requests:
            cpu: 100m
            memory: 3Gi
          limits:
            cpu: 250m
        ports:
          - containerPort: 80
            name: pmc-port
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /api/
            port: pmc-port
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: pmc-secrets-volume
          mountPath: "/mnt/secrets"
          readOnly: true
        envFrom:
          - configMapRef:
              name: pmc-settings
      - name: pulp-api
        image: $loginserver/pulp:latest
        command: ['/pulp-common-entrypoint.sh', 'pulp-api']
        resources:
          requests:
            cpu: 100m
            memory: 3Gi
          limits:
            cpu: 250m
        ports:
        - containerPort: 24817
          name: pulp-api-port
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /pulp/api/v3/status/
            port: pulp-api-port
          initialDelaySeconds: 60
          periodSeconds: 10
        volumeMounts:
          - name: pulp-secrets-volume
            mountPath: "/mnt/secrets"
            readOnly: true
        envFrom:
          - configMapRef:
              name: pulp-settings
      volumes:
        - name: pulp-secrets-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "pulp-secret-provider"
        - name: pmc-secrets-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "pmc-secret-provider"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-pod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pod
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pmc-service-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: pmc