apiVersion: v1
kind: ConfigMap
metadata:
  name: pmc-settings
data:
  API_PREFIX: "/api/v4"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "80"
  DEBUG: "0"
  PULP_ADMIN_USERNAME: "admin"
  APP_CLIENT_ID: $pmcAppId
  TENANT_ID: $AZURE_TENANT_ID
  POSTGRES_USER: "pmcserver"
  POSTGRES_DB: "pmcserver"
  PULP_HOST: "http://localhost:24817"  # pmc-server talks to pulp api via in-pod localhost
  POSTGRES_SERVER: $pg_server
  POSTGRES_SERVER_CA_CERT: "/pmcserver/root-cert-bundle.pem"
  SECRETS_MOUNTPOINT: "/mnt/secrets"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pulp-settings
data:
  SECRETS_MOUNTPOINT: "/mnt/secrets"
  PULP_DB_ENCRYPTION_KEY: "/mnt/secrets/pulpSymmetricKey"
  PULP_TOKEN_AUTH_DISABLED: "true"
  PULP_TELEMETRY: "false"
  PULP_CONTENT_ORIGIN: "http://${destination_env}:80"
  POSTGRES_SERVICE_HOST: $pg_server
  PULP_DATABASES__default__HOST: $pg_server
  SIGNER_HOST: "localhost"
  PULP_AZURE_ACCOUNT_NAME: $bstg
  PULP_AZURE_CONTAINER: "pulp"
  PULP_AZURE_URL_EXPIRATION_SECS: "3600"
  # PULP_AZURE_API_VERSION="2021-08-06"
  PULP_DEFAULT_FILE_STORAGE: "storages.backends.azure_storage.AzureStorage"
  PULP_MEDIA_ROOT: ""
  PULP_AZURE_LOCATION: ""
  PULP_AZURE_OVERWRITE_FILES: "true"
  PULP_CONTENT_PATH_PREFIX: "/"
  PULP_PUBLISH_RELEASE_FILE_LABEL: "true"
  PULP_CONTENT_WORKERS: "8"
  # Long enough to let tasks complete, a little less than AKS terminationGracePeriodSeconds
  PULP_WORKER_TTL: "300"
  PULP_DATABASES__default__OPTIONS__sslmode: "verify-full"
  PULP_DATABASES__default__OPTIONS__sslrootcert: "/usr/bin/root-cert-bundle.pem"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: signer-settings
data:
  KEYVAULT: $kv
  SIGN_CERT: $esrpSignCert
  AUTH_CERT_PATH: $esrpAuthCertPath
  LEGACY_KEY_PATH: "/mnt/secrets/legacy-sign"
  LEGACY_KEY_THUMBPRINT: $legacyKeyThumprint
  APP_ID: $esrp_app_id
  TENANT_ID: $AZURE_TENANT_ID
  KEY_CODES: $esrpKeyCode
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pmc-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $CLIENT_ID
    keyvaultName: $kv
    # This configures what secrets we pull from the keyvault
    objects: |
      array:
        - |
          objectName: "pulpPostgresPassword"
          objectType: secret
        - |
          objectName: "pmcPostgresPassword"
          objectType: secret
        - |
          objectName: "pulpAdminPassword"
          objectType: secret
        - |
          objectName: "afQueueActionUrl"
          objectType: secret
        - |
          objectName: "afFailureUrl"
          objectType: secret
    tenantId: $AZURE_TENANT_ID
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pulp-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $CLIENT_ID
    keyvaultName: $kv
    # This configures what secrets we pull from the keyvault
    objects: |
      array:
        - |
          objectName: "pulpPostgresPassword"
          objectType: secret
        - |
          objectName: "pulpAdminPassword"
          objectType: secret
        - |
          objectName: "pulpSecret"
          objectType: secret
        - |
          objectName: "pulpSymmetricKey"
          objectType: secret
        - |
          objectName: "pulpBlobStorageKey"
          objectType: secret
    tenantId: $AZURE_TENANT_ID
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: signer-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $CLIENT_ID
    keyvaultName: $kv
    # This configures what secrets we pull from the keyvault
    objects: |
      array:
        - |
          objectName: $esrpAuthCert
          objectType: secret
        - |
          objectName: "legacy-sign"
          objectType: secret
    tenantId: $AZURE_TENANT_ID
