[cli]
no_wait = false
no_color = false
id_only = false
format = "json"
debug = false
base_url = "https://pmc-ingest.trafficmanager.net/api/v4"
msal_client_id = "YOUR_CLIENT_ID"
msal_scope = "api://d48bb382-20ec-41b9-a0ea-07758a21ccd0/.default"
msal_cert_path = "/PATH/TO/YOUR/CERT"
msal_SNIAuth = true
msal_authority = "https://login.microsoftonline.com/MSAzureCloud.onmicrosoft.com"
