"""repo access and package ownership uniq constraints

Revision ID: 067f450caa29
Revises: 19b2f4b674fc
Create Date: 2022-08-18 17:22:39.938462

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '067f450caa29'
down_revision = '19b2f4b674fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ownedpackage', ['account_id', 'repo_id', 'package_name'])
    op.create_unique_constraint(None, 'repoaccess', ['account_id', 'repo_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repoaccess', type_='unique')
    op.drop_constraint(None, 'ownedpackage', type_='unique')
    # ### end Alembic commands ###
