"""account_role

Revision ID: 19b2f4b674fc
Revises: cedc71e8ee67
Create Date: 2022-07-08 18:55:34.542820

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19b2f4b674fc'
down_revision = 'cedc71e8ee67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('role', sa.Enum('Publisher', 'Account_Admin', 'Repo_Admin', 'Package_Admin', name='role'), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('icm_service', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icm_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_table('ownedpackage',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('package_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownedpackage_id'), 'ownedpackage', ['id'], unique=False)
    op.create_table('repoaccess',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operator', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repoaccess_id'), 'repoaccess', ['id'], unique=False)
    op.drop_index('ix_publisher_id', table_name='publisher')
    op.drop_table('publisher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_edited', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_account_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_repo_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_package_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('icm_service', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('icm_team', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='publisher_pkey'),
    sa.UniqueConstraint('name', name='publisher_name_key')
    )
    op.create_index('ix_publisher_id', 'publisher', ['id'], unique=False)
    op.drop_index(op.f('ix_repoaccess_id'), table_name='repoaccess')
    op.drop_table('repoaccess')
    op.drop_index(op.f('ix_ownedpackage_id'), table_name='ownedpackage')
    op.drop_table('ownedpackage')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_table('account')
    op.execute('drop type role')
    # ### end Alembic commands ###
