"""changeable_oid

Revision ID: 1f2ce48deb08
Revises: 45dc84923230
Create Date: 2022-09-20 14:48:10.021534

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "1f2ce48deb08"
down_revision = "45dc84923230"
branch_labels = None
depends_on = None


def upgrade():
    # Since we're altering the value of the primary / foreign key, we have to either have a
    # complicated migration or just wipe all related data. Let's just wipe all related data.
    op.execute("truncate table account cascade")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("oid", sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_unique_constraint(None, "account", ["oid"])
    # ### end Alembic commands ###


def downgrade():
    # Since we're altering the value of the primary / foreign key, we have to either have a
    # complicated migration or just wipe all related data. Let's just wipe all related data.
    op.execute("truncate table account cascade")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "account", type_="unique")
    op.drop_column("account", "oid")
    # ### end Alembic commands ###
