"""Adding Signature column to the account table

Revision ID: 67e1db85fafd
Revises: 1f2ce48deb08
Create Date: 2023-04-04 15:08:27.827095

"""
from alembic import op
from app.core.models import Account
from sqlalchemy.orm import Session
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '67e1db85fafd'
down_revision = '1f2ce48deb08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    session = Session(bind=conn)

    op.add_column("account", sa.Column("signature", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    for item in session.query(Account):
        item.sign()
    session.commit()
    
    op.alter_column("account", "signature", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "signature")
    # ### end Alembic commands ###
